### PR TITLE
Add 57 linux games

### PR DESCRIPTION
**Pull request by basxto**
There were also some corrections for executable detection and save path filters.
A few games were also tested with alternate versions from GOG and Humble.

### CODE REVIEW

**Comment by MikeMaximus** [comment]
That's a big update.  Thanks basxto!

**Comment by basxto** [comment]
Some commits are from february, when the regex support wasn’t released.
And I was too lazy to upgrade my database and fix all game ids, some where steam ids and some where out of sync after 1.1.



I have > 200 games tagged with `incomplete`, where I either failed to detect the game, did not find the savegames or wasn’t able to tell GBM the location of the saves.

I regret publishing `Star Wars: Dark Forces`, because it does lose the savegame when uninstalled.

I also had to list one game twice, since steam and gog version use different save locations. Sometimes backups only work with the drm-free version. Maybe it would be helpful to warn when a game only gets tracked or no files changed in the backup. Sometimes I’m able to backup all versions, but each version plays on a differently named savegame. But since comments get exported now, I’ll just put such explanations there.

I have 500 linux games in steam alone, 100 drm-free on gog (mostly the same), likely >100 of drm-free games on humble. There should be also a few drm-free games on desura and groupees.

So there is still much to add and test.
Next I will check all official games which do only tracking and find better solutions unless they are multiplayer games. At least I will always explain why there is no backup.

Do you use `multiple backups` for official games? And maybe you can update your DOSBox games on GOG, since with parameter detection those games can be distinguished now.

**Comment by MikeMaximus** [comment]
I hope you didn't update all the IDs manually,  "Tools -> Sync Game IDs" with the prior official list should have worked unless you changed the game name's extensively.

For game configurations that only do tracking I just add a Tracking tag to them for the Windows list.  This flags it with a clock icon on the website, I also need to change how those games get their data displayed on the style sheet since those configs dont use most fields.

Yeah I need to do a lot of updates on the Windows list to support parameters and regex, I've only done the few that I happened to still have installed.

No the "Multiple Backups" option is not part of the core configuration fields and not exported.  I felt it was a subjective option and couldn't think of a reason why I'd need to force it for a game on the official list.

**Comment by basxto** [comment]
> I hope you didn't update all the IDs manually, "Tools -> Sync Game IDs" with the prior official list should have worked unless you changed the game name's extensively.

I luckily found that option, but I had to fix 20 or so manually.

> No the "Multiple Backups" option is not part of the core configuration fields and not exported. I felt it was a subjective option and couldn't think of a reason why I'd need to force it for a game on the official list.

Maybe for games with just one savegame

> For game configurations that only do tracking I just add a Tracking tag to them for the Windows list. This flags it with a clock icon on the website, I also need to change how those games get their data displayed on the style sheet since those configs dont use most fields.

Ah okay, I’m adding icons for  itch.io and humble and I will also touch that area.
But I change it so, that the clock only appears when `MonitorOnly` is active.
Otherwise it will be redundant and error prone.

**Comment by MikeMaximus** [comment]
Yeah it may be better to just check MonitorOnly.  I can update the import window to also flag those configurations with a special icon or tag as well instead of using a custom tag.

**Pull request merged**
