### PR TITLE
More Linux games

### PR DESCRIPTION
**Pull request by basxto**
Add 52 Linux games
Introduce SteamCloud tag

### CODE REVIEW

**Comment by MikeMaximus** [comment]
I noticed the following games are using an absolute path to the steam folder.  Could they use a relative path instead?  I don't have any of them to test.

Iesabel
Kingdom Rush
Knights of Pen and Paper +1
Retro City Rampage

**Comment by basxto** [comment]
Yes, you are right.
Especially since I moved my steam library since then.
Retro City Rampage does not work, since `../` causes GBM to hang itself. (The executable is run in a subdirectory)

**Comment by basxto** [comment]
Okay, Retro City Rampage does work, but during backup GBM froze for a minute or so.
The is backup’s size is just 4.7KiB.

Is this probably related to the calculation of the backup’s size?

**Comment by MikeMaximus** [comment]
Yeah very likely.  Is RCR one of those games with thousands of files?

Folder size calculations should be accurate and never freeze completely anymore,  but it's very inefficient in that it always looks at the entire save folder regardless of settings.  I need to spend some time on that.

**Comment by basxto** [comment]
It’s not, the whole folder is also only 23MiB big.

```console
$ tree /mnt/olhdd/steam/steamapps/common/Retro\ City\ Rampage/
/mnt/olhdd/steam/steamapps/common/Retro City Rampage/
├── audio_music_Linux.bap
├── audio_sfx_Linux.bap
├── gamedata_sdl.bfp
├── i386
│   ├── libsteam_api.so
│   └── retrocityrampage
├── profile.rsv
├── rcr_sdl.cfg
├── readme.txt
├── retrocityrampage
├── RetroCityRampage486_MS-DOS_v1.0.zip
├── rtsave0.rsv
├── rtsave1.rsv
├── rtsave2.rsv
└── x86_64
    ├── libsteam_api.so
    └── retrocityrampage

2 directories, 15 files
```

I rather suspect there’s something going wrong when you use `../` relative to the working directory of the application.

**Comment by MikeMaximus** [comment]
Odd, a folder that size should be instantaneous. 

Are you positive that "../" is needed?  I ask because it looks like there's three binaries, one in the root with the saves, and then two platform specific ones in sub-directories and all using the same name.  

I suspect that GBM may be seeing the process path as "/mnt/olhdd/steam/steamapps/common/Retro City Rampage/" instead of one of the sub-directories and a "../" save path is making it scan your entire steam app folder.  The backup would still look successful because maybe those are the only rsv files found in any sub-directory, it would just take a lot longer for both GBM and 7z to deal with that kind of configuration.

**Comment by basxto** [comment]
I track `retrocityrampage` and GBM detects as Game Path `/mnt/olhdd/steam/steamapps/common/Retro City Rampage/x86_64`
```console
$  ps ax | grep retro
16550 ?        S      0:00 bash /mnt/olhdd/steam/steamapps/common/Retro City Rampage/retrocityrampage
16552 ?        Sl     0:02 ./x86_64/retrocityrampage 
```

**Comment by MikeMaximus** [comment]
Well that sounds fine, but it's definitely doing something weird.  I'll build a test folder structure to see if i can replicate this.  

GBM should show the path being backed up in the log when it starts.  Is it showing the correct path?

**Comment by basxto** [comment]
I just noticed, that I was still on 1.0.2, but it loosk the same on 1.0.4.

```
[18.11.2017 14:11:33] Retro City Rampage Detected
[18.11.2017 14:11:51] Retro City Rampage has ended.
[18.11.2017 14:11:51] A sync to the master game list has been triggered.
[18.11.2017 14:11:51] 1 change(s) synced.
[18.11.2017 14:15:52] Available Disk Space: 97,33 GB
[18.11.2017 14:15:52] Retro City Rampage Save Folder Size: 300,11 KB
[18.11.2017 14:15:56] Backup of /mnt/olhdd/steam/steamapps/common/Retro City Rampage/x86_64/../ in progress...

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=de_DE.utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz (306A9),ASM,AES-NI)

Scanning the drive:
4 files, 5120 bytes (5 KiB)

Creating archive: /home/dabascht/game_backup_monitor/savegames/Retro City Rampage/Retro City Rampage.7z

Items to compress: 4


Files read from disk: 4
Archive size: 4835 bytes (5 KiB)
Everything is Ok
[18.11.2017 14:15:57] Retro City Rampage backup (4,72 KB) completed. 
[18.11.2017 14:15:57] Generating SHA-256 hash for Retro City Rampage backup file.
```

**Comment by MikeMaximus** [comment]
I was able spend more time debugging this morning, and wow I apologize for this one.  I'm not sure how I never encountered this myself. 

It's a pretty blatant bug with any relative path configuration.  It's not building the path correctly before it's given to the folder size function.  In your case i suspect it's interpreting it as starting from root, which is why it takes 4 minutes to process.

We can move the discussion to this [issue](https://github.com/MikeMaximus/gbm/issues/104) in the GBM project instead.

**Pull request merged**
